name: Test

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "head"
        
        experimental: [false]
        
        # include:
        #   - os: ubuntu
        #     ruby: truffleruby
        #     experimental: true
        #   - os: ubuntu
        #     ruby: jruby
        #     experimental: true
        #   - os: ubuntu
        #     ruby: head
        #     experimental: true
    
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Run tests
      timeout-minutes: 2
      run: bundle exec rake
